---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: nginx
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      nginx: enabled 
  resources:
  - kind: ConfigMap
    name: nginx-configmap-namespace
  - kind: ConfigMap
    name: nginx-configmap-deployment

