---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: wordpress
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      wordpress: enabled 
  resources:
  - kind: ConfigMap
    name: local-path-configmap
  - kind: ConfigMap
    name: wordpress-configmap-namespace
  - kind: ConfigMap
    name: wordpress-configmap-mysql
  - kind: ConfigMap
    name: wordpress-configmap-deployement

