apiVersion: v1
data:
  namespace.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: wordpress
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: wordpress-configmap-namespace
